version: '3'
services:
  nginx:
    image: nginx:1.15.3-alpine
    container_name: app_nginx
    volumes:
      - ${SYMFONY_APP}:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: app_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: .docker/php
    container_name: app_php
    volumes:
      - ${SYMFONY_APP}:/var/www/app
    environment:
      - maildev_host=app_maildev
    depends_on:
      - maildev
      - mysql
    user: 1000:1000
    ports:
      - 9000:9000

  node:
    build: .docker/node
    container_name: app_node
    ports:
      - 4200:4200
    volumes:
      - ${ANGULAR_APP}:/home/node/app/frontend
    command:
      - /bin/sh
      - -c
      - |
          cd /home/node/app/frontend && npm install && npm start

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: app_maildev
    ports:
      - 8001:80
